
<?= $this->flashMessenger()->render('default', array('alert', 'alert-dismissible', 'alert-warning')); ?>

<div class="page-header">
    <a href="<?= $this->url('administration/tags', ['action' => 'add']); ?>" class="btn btn-primary btn-sm" role="button">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        Add
    </a>
</div>
<div>
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>id</th>
            <th>name</th>
            <th>action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($entities as $entity): ?>
            <tr>
                <td><?= $entity->getId(); ?></td>
                <td><?= $entity->getName(); ?></td>
                <td>
                    <a href="<?= $this->url('administration/tags', ['action' => 'delete', 'id' => $entity->getId()]); ?>" class="btn btn-sm" role="button">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        Delete
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?= $this->paginationControl($entities, 'sliding', 'partial/paginator.phtml', ['route' => 'administration/tagsPagination']); ?>
</div>