<?php
/* @var $container Zend\Navigation\Navigation */
$container   = $this->container;
$currentPage = $container->findOneBy('active', 1);
?>

<div class="container menu">

    <ul class="<?php echo $this->navigation($container)->menu()->getUlClass(); ?>">
        <?php foreach ($container as $page): ?>
            <li class="menu-item">
                <a href="<?= $page->getHref() ?>"><?= $page->getLabel() ?>
                    <div class="item-title"></div>
                    <div class="menu-arrow"></div>
                </a>
            </li>
        <?php endforeach ?>
    </ul>

</div>

<?php if ($currentPage) : ?>
<div class="container container-panel container-panel-contact" style="background-color: <?= $currentPage->getCustomProperties()['color']; ?>">
    <div class="panel-title">
        <h1><?= $currentPage->getLabel(); ?></h1>
    </div>
</div>
<div class="container">
    <p class="v-margin"><?= $currentPage->getTitle() ?></p>
</div>
<?php endif; ?>