<p>Are you sure that you want to delete ?</p>
<div class="form-group row col-lg-8">
    <?php echo $this->escapeHtml($question->getText()); ?>
</div>

<div class="form-group row col-lg-8">
    <form action="<?= $this->url('administration/questions', ['action' => 'delete', 'testId' => $testId, 'questionId' => $questionId]); ?>" method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo (int) $question->getId(); ?>" />
            <input type="submit" name="del" value="Yes" />
            <input type="submit" name="del" value="No" />
        </div>
    </form>
</div>