<?= $this->flashMessenger()->render('default', array('alert', 'alert-dismissible', 'alert-warning')); ?>

<div class="page-header">
<a href="<?= $this->url('administration/questions', ['action' => 'add', 'testId' => $testId]); ?>" class="btn btn-primary btn-sm" role="button">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    Add a question
</a>
</div>
<div>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>id</th>
                <th>Text</th>
                <th>created</th>
                <th>action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($questions as $question): ?>
            <tr>
                <td><?= $question->getId(); ?></td>
                <td><?= substr($question->getText(), 0, 30); ?></td>
                <td><?= $question->getCreated() !== null ? $question->getCreated()->format('Y-m-d H:i') : '-'; ?></td>
                <td>
                    <a href="<?= $this->url('administration/questions', ['action' => 'edit', 'testId' => $testId, 'questionId' => $question->getId()]); ?>" class="btn btn-sm" role="button">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                        Edit
                    </a>

                    <a href="<?= $this->url('administration/questions', ['action' => 'delete', 'testId' => $testId, 'questionId' => $question->getId()]); ?>" class="btn btn-sm" role="button">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        Delete
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>