<div class="container container-panel container-panel-faq">
    <div class="panel-title"><h1>questions fréquentes</h1></div>
</div>

<div class="container faq">
    <div class="row v-margin">
        <ul>

            <li>
                <h3>Qui sommes-nous ?</h3>
                <p>
                    Ce site est le fruit de la collaboration de spécialistes du code de la route et de talentueux développeurs.
                    Pour faire simple, nous avons tous un jour ont passé notre permis et on se souvient tous à quel point
                    c'était compliqué en plus d'être un gouffre financier.
                    Notre idée alors c'était d'aider les jeunes et les moins jeunes à obtenir leur code de la route.
                    Alors voilà notre site qui vous permet de vous entrainer à volonté sur les questions du code de la route. Tout ça gratuitement !
                </p>
            </li>

            <li>
                <h3>Pourquoi c'est gratuit ?</h3>
                <p>
                    En effet le site est ouvert à tous et est 100% gratuit. D'ailleurs pour votre confort, il n'y a pas de publicité.<br>
                    Nous ne sommes pas pingres. Nous croyons à l'entr'aide.
                    D'ailleurs le web révolutionne le monde et nous essayons à notre manière d'en faire parti.
                </p>
            </li>

            <li>
                <h3>Comment puis-je vous contacter ?</h3>
                <p>
                    Vous pouvez nous contacter en remplissant ce <a href="<?= $this->url('home/contact') ?>">formulaire</a>. N'hésitez surtout pas
                    à nous donnez vos impressions. Ce site est fait pour vous.
                </p>
            </li>

            <li>
                <h3>Y aura-t-il de nouveaux tests ?</h3>
                <p>
                    Oui. Tous les jours nous rajoutons de nouveaux tests.
                </p>
            </li>

            <li>
                <h3>J'aime votre site, comment pourrai-je vous soutenir ?</h3>
                <p>
                    Liker et Tweeter notre site web via les réseaux sociaux. Cela aidera à nous faire connaitre et fera grandir la communauté.
                </p>
            </li>

        </ul>

        <ul class="social-sharing list-inline" data-permalink="<?= $this->serverUrl(); ?>">
            <li>
                <a target="_blank" href="http://plus.google.com/share?url=<?= $this->serverUrl(); ?>" class="share-google">
                    <span class="icon icon-google" aria-hidden="true"></span>
                    <span class="share-title">+1</span>
                </a>
            </li>

            <li>
                <a target="_blank" href="http://twitter.com/share?url=<?= $this->serverUrl(); ?>" class="share-twitter">
                    <span class="icon icon-twitter" aria-hidden="true"></span>
                    <span class="share-title">Tweet</span>
                </a>
            </li>

            <li>
                <a target="_blank" href="http://www.facebook.com/sharer.php?u=<?= $this->serverUrl(); ?>" class="share-facebook">
                    <span class="icon icon-facebook" aria-hidden="true"></span>
                    <span class="share-title">Share</span>
                </a>
            </li>
        </ul>

    </div>
</div>