<div class="container container-panel container-panel-faq">
    <div class="panel-title"><h1>questions fréquentes</h1></div>
</div>

<div class="container faq">
    <div class="row v-margin">
        <ul>

            <li>
                <h3>Qui sommes-nous ?</h3>
                <p>
                    Pour faire simple, nous sommes une petite équipe de passionné du web qui un jour ont passé leur permis
                    et se sont rendu compte que c'était non seulement compliqué mais aussi un gouffre financier.
                    Notre idée alors c'était d'aider les jeunes et les moins jeunes à obtenir leur permis du code de la route.
                    Alors voila notre site qui vous permet de vous entrainer à volonté sur les questions du permis. Tout ça gratuitement !
                </p>
            </li>

            <li>
                <h3>Pourquoi c'est gratuit ?</h3>
                <p>
                    Parce que nous ne sommes pas pingres. Nous croyons à l'entr'aide. <br>
                    D'ailleurs le web révolutionne le monde et nous essayons à notre manière d'en faire parti.
                </p>
            </li>

            <li>
                <h3>Comment puis-je vous contacter ?</h3>
                <p>
                    Vous pouvez nous contacter en remplissant ce <a href="<?= $this->url('home/contact') ?>">formulaire</a>. N'hésitez surtout pas
                    à nous donnez vos impressions. Ce site est fait pour vous.
                </p>
            </li>

            <li>
                <h3>Y aura-t-il de nouveaux tests ?</h3>
                <p>
                    Oui. Tous les jours nous rajoutons de nouveaux tests.
                </p>
            </li>

            <li>
                <h3>J'aime votre site, comment pourrai-je vous soutenir ?</h3>
                <p>
                    Likez notre site web via les réseaux sociaux. Cela nous aidera à nous faire connaitre et fera grandir notre communauté.
                </p>
            </li>

        </ul>

    </div>
</div>