<?php
$form = $this->form;
?>

<div class="container container-panel container-panel-contact">
    <div class="panel-title"><h1>nous contacter</h1></div>
</div>

<div class="container">
    <div class="row v-margin">
        Vous pouvez nous laisser un message en remplissant ce formulaire.<br>
        On sera ravi de vous répondre.
    </div>
</div>

<div class="container container-contact">
    <?= $this->form()->openTag($form); ?>

        <div class="form-group row">
            <div class="col-sm-8">
                <div>
                    <?= $this->formRow($form->get('name')->setAttributes(['class' => 'form-control', 'placeholder' => 'Votre nom'])); ?>
                </div>
            </div>
        </div>

        <div class="form-group row row">
            <div class="col-sm-8">
                <div>
                    <?= $this->formRow($form->get('email')->setAttributes(['class' => 'form-control', 'placeholder' => 'Votre email'])); ?>
                </div>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-8">
                <div>
                    <?= $this->formRow($form->get('message')->setAttributes(['class' => 'form-control', 'rows' => '6', 'placeholder' => 'Votre message'])); ?>
                </div>
            </div>
        </div>

        <div class="form-group row row-captcha">
            <div class="col-sm-8">
                <div>
                    <?= $this->formRow($form->get('captcha')->setAttributes(['class' => 'form-control'])); ?>
                </div>
            </div>
        </div>

        <?= $this->formRow($form->get('csrf')); ?>

        <div class="form-group row">
            <div class="col-sm-8">
                <div>
                    <input type="submit" name="submit" id='contact-button' class="round-button pull-right" value="envoyer">
                </div>
            </div>
        </div>

    <?= $this->form()->closeTag(); ?>

</div>