<?php
$form->setAttribute('action', $this->url('administration/posts', array('action' => 'add')));
$form->get('submit')->setValue('Add');
$form->prepare();
?>

<div class="page-header">
    <h3>Add Post</h3>
</div>
<?= $this->form()->openTag($form); ?>
<?= $this->formHidden($form->get('id')); ?>

    <div class="form-group row">
        <div class="col-lg-8">
            <label>Title</label>
            <?= $this->formRow($form->get('title')); ?>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-lg-8">
            <label>Image</label>
            <?= $this->formRow($form->get('image')); ?>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-lg-8">
            <label>Text</label>
            <?= $this->formRow($form->get('text')); ?>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-lg-8">
            <label>Url</label>
            <?= $this->formRow($form->get('url')); ?>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-lg-8">
            <label">Tags</label>
            <div>
                <?= $this->formRow($form->get('tags')); ?>
            </div>
        </div>
    </div>

<?= $this->formSubmit($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>