<h1><?php echo $this->escapeHtml($post->getTitle()); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($post->getTitle()); ?>' by
    '<?php echo $this->escapeHtml($post->getText()); ?>'?
</p>

<form action="<?= $this->url('administration/posts', ['action' => 'delete', 'id' => $this->id]); ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $post->getId(); ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>