<?php
$form->setAttribute('action', $this->url('administration/posts', ['action' => 'edit', 'id' => $id]));
$form->get('submit')->setValue('Edit');
$form->prepare();
$image = $form->get('image')->getValue();
?>

<div class="page-header">
    <h3>Edit Post</h3>
</div>

<?= $this->form()->openTag($form); ?>
<?= $this->formHidden($form->get('id')); ?>

    <div class="form-group row">
        <div class="col-lg-8">
            <label>Title</label>
            <?= $this->formRow($form->get('title')); ?>
        </div>
    </div>

    <?php if (! empty($image)): ?>
    <div class="form-group row col-lg-8">
        <img src="/img/upload/<?= $image;?>" class="img-thumbnail"/>
    </div>
    <?php endif; ?>

    <div class="form-group row">
        <div class="col-lg-8">
            <label>Image</label>
            <?= $this->formRow($form->get('image')); ?>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-lg-8">
            <label>Text</label>
            <?= $this->formRow($form->get('text')); ?>
        </div>
    </div>

    <div data-text-angular="" data-ng-model="content"></div>

    <div class="form-group row">
        <div class="col-lg-8">
            <label>Tags</label>
            <div>
                <?= $this->formRow($form->get('tags')); ?>
            </div>
        </div>
    </div>

<?= $this->formSubmit($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>