
<?= $this->flashMessenger()->render('default', array('alert', 'alert-dismissible', 'alert-warning')); ?>

<div class="page-header">
<a href="posts/add" class="btn btn-primary btn-sm" role="button">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    Add
</a>
</div>
<div>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>id</th>
                <th>title</th>
                <th>text</th>
                <th>created</th>
                <th>updated</th>
                <th>action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($providers as $provider): ?>
            <tr>
                <td><?= $provider->getId(); ?></td>
                <td><?= $provider->getTitle(); ?></td>
                <td><?= $provider->getText(); ?></td>
                <td><?= $provider->getCreated() !== null ? $provider->getCreated()->format('Y-m-d H:i:s') : '-'; ?></td>
                <td><?= $provider->getUpdated() !== null ? $provider->getUpdated()->format('Y-m-d H:i:s') : '-'; ?></td>
                <td>
                    <a href="<?= $this->url('administration/posts', ['action' => 'edit', 'id' => $provider->getId()]); ?>" class="btn btn-sm" role="button">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                        Edit
                    </a>

                    <a href="<?= $this->url('administration/posts', ['action' => 'delete', 'id' => $provider->getId()]); ?>" class="btn btn-sm" role="button">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        Delete
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>