
<?= $this->flashMessenger()->render('default', array('alert', 'alert-dismissible', 'alert-warning')); ?>

<div class="page-header">
<a href="<?= $this->url('administration/posts', ['action' => 'add']); ?>" class="btn btn-primary btn-sm" role="button">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    Add
</a>
</div>
<div>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>id</th>
                <th>title</th>
                <th>text</th>
                <th>created</th>
                <th>updated</th>
                <th>action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($posts as $post): ?>
            <tr>
                <td><?= $post->getId(); ?></td>
                <td><?= substr($post->getTitle(), 0, 30); ?></td>
                <td><?= substr($post->getText(), 0, 70); ?></td>
                <td><?= $post->getCreated() !== null ? $post->getCreated()->format('Y-m-d H:i') : '-'; ?></td>
                <td><?= $post->getUpdated() !== null ? $post->getUpdated()->format('Y-m-d H:i') : '-'; ?></td>
                <td>
                    <a href="<?= $this->url('administration/posts', ['action' => 'edit', 'id' => $post->getId()]); ?>" class="btn btn-sm" role="button">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                        Edit
                    </a>

                    <a href="<?= $this->url('administration/posts', ['action' => 'delete', 'id' => $post->getId()]); ?>" class="btn btn-sm" role="button">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        Delete
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?= $this->paginationControl($posts, 'sliding', 'partial/paginator.phtml', ['route' => 'administration/pagination']); ?>
</div>