
<?= $this->flashMessenger()->render('default', array('alert', 'alert-dismissible', 'alert-warning')); ?>

<div class="page-header">
<a href="<?= $this->url('administration/posts', ['action' => 'add']); ?>" class="btn btn-primary btn-sm" role="button">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    Add
</a>
</div>
<div>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>id</th>
                <th>title</th>
                <th>text</th>
                <th>created</th>
                <th>updated</th>
                <th>action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($posts as $post): ?>
            <tr>
                <td><?= $post->getId(); ?></td>
                <td><?= $post->getTitle(); ?></td>
                <td><?= $post->getText(); ?></td>
                <td><?= $post->getCreated() !== null ? $post->getCreated()->format('Y-m-d H:i:s') : '-'; ?></td>
                <td><?= $post->getUpdated() !== null ? $post->getUpdated()->format('Y-m-d H:i:s') : '-'; ?></td>
                <td>
                    <a href="<?= $this->url('administration/posts', ['action' => 'edit', 'id' => $post->getId()]); ?>" class="btn btn-sm" role="button">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                        Edit
                    </a>

                    <a href="<?= $this->url('administration/posts', ['action' => 'delete', 'id' => $post->getId()]); ?>" class="btn btn-sm" role="button">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        Delete
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?php
    // add at the end of the file after the table
    echo $this->paginationControl(
    // the paginator object
        $posts,
        // the scrolling style
        'sliding',
        // the partial to use to render the control
        'partial/paginator.phtml',
        // the route to link to when a user clicks a control link
        array(
            'route' => 'administration/pagination'
        )
    );
    ?>
</div>