<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Quizz'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/blog.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/script.js')
            ->prependFile($this->basePath() . '/js/angular/services.js')
            ->prependFile($this->basePath() . '/js/angular/filters.js')
            ->prependFile($this->basePath() . '/js/angular.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

        <link href='http://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>

    </head>
    <body  ng-app="quizz">


        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">

                    <?php if (! ($this->identity() && $this->identity()->getRole() === 'subscriber')) :?>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <?php endif; ?>

                    <a class="navbar-brand" href="<?= $this->url('home') ?>">Marvelous Quizz</a>
                </div>

                <?php if (! ($this->identity() && $this->identity()->getRole() === 'subscriber')) :?>
                    <?php $formLogin->prepare()->setAttributes([
                        'class'     => 'navbar-form navbar-right',
                        'action'    => $this->url('home/login', ['params'=>['action'=>'login']]),
                    ]); ?>
                    <div id="navbar" class="navbar-collapse collapse">
                        <?= $this->form()->openTag($formLogin); ?>
                            <div class="form-group">
                                <?= $this->formRow($formLogin->get('login')->setAttributes(['class'=>'form-control', 'placeholder'=>'Email'])); ?>
                            </div>
                            <div class="form-group">
                                <?= $this->formRow($formLogin->get('password')->setAttributes(['class'=>'form-control', 'placeholder'=>'Password'])); ?>
                            </div>
                            <button type="submit" class="btn btn-success">Connexion</button>
                        <?= $this->form()->closeTag(); ?>
                    </div><!--/.navbar-collapse -->
                <?php else : ?>
                    <ul class="nav navbar-nav navbar-right connected">
                        <li><?= $this->identity()->getFirstname() ?></li>
                        <li><?= $this->identity()->getLastname() ?></li>
                        <li><span class="glyphicon glyphicon-check" aria-hidden="true"></span></li>
                    </ul>
                <?php endif; ?>

            </div>
        </nav>


        <?= $this->content; ?>


        <?php echo $this->inlineScript() ?>
    </body>
</html>
