<?php
$form->setAttribute('action', $this->url('administration/tests', ['action' => 'add']));
$form->prepare();
$form->get('submit')->setValue('Add');

$test = $form->get('test');
$image = $test->get('image')->getValue();

?>

<div class="page-header">
    <h3>Add Test</h3>
</div>

<?= $this->form()->openTag($form); ?>
<?= $this->formHidden($test->get('id')); ?>

    <div class="form-group row">
        <div class="col-lg-8">
            <label>Tags</label>
            <div>
            <?= $this->formRow($test->get('tags')); ?>
            </div>
        </div>
    </div>

    <?php if (! empty($image)): ?>
    <div class="form-group row col-lg-8">
        <img src="/img/upload/<?= $image;?>" class="img-thumbnail"/>
    </div>
    <?php endif; ?>


    <div class="form-group row">
        <div class="col-lg-8">
            <label>Image</label>
            <?= $this->formRow($test->get('image')); ?>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-lg-8">
            <label>Explanation</label>
            <?= $this->formRow($test->get('explanation')->setAttributes(['class' => 'form-control'])); ?>
        </div>
    </div>

    <div onclick="return add_question()">Add a new question</div>

    <div class="form-group row" >
        <div class="col-lg-8">
            <label>Questions</label>
            <div id="questions">
                <?= $this->formCollection($test->get('questions')); ?>
            </div>
        </div>
    </div>

<input type="submit" name="submit" id="submitbutton" class="btn btn-default" value="Add" onclick="disableEmptyInput()">
<?= $this->form()->closeTag(); ?>

<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>

<script>
    function add_question() {
        var currentCount = $('#questions > fieldset > fieldset').length;
        var template = $('#questions fieldset span').data('template');
        template = template.replace(/__index-question__/g, currentCount);
        $('#questions > fieldset').append(template);
        return false;
    }

    function disableEmptyInput() {
        // disable every empty option-inputs
        $('.option-input[type=text]').each(function(index) {
            if (! $(this).val().trim()) {
                $(this).siblings('input').prop('disabled', true);
                $(this).prop('disabled', true);
            }
        });
    }
</script>