<?php
$form->setAttribute('action', $this->url('administration/tests', ['action' => 'add']));
$form->prepare();
$form->get('submit')->setValue('Add');

$test = $form->get('test');
$image = $test->get('image')->getValue();

?>

<div class="page-header">
    <h3>Add Test</h3>
</div>

<?= $this->form()->openTag($form); ?>
<?= $this->formHidden($test->get('id')); ?>

    <div class="form-group row">
        <div class="col-lg-8">
            <label>Tags</label>
            <div>
            <?= $this->formRow($test->get('tags')); ?>
            </div>
        </div>
    </div>

    <?php if (! empty($image)): ?>
    <div class="form-group row col-lg-8">
        <img src="/img/upload/<?= $image;?>" class="img-thumbnail"/>
    </div>
    <?php endif; ?>


    <div class="form-group row">
        <div class="col-lg-8">
            <label>Image</label>
            <?= $this->formRow($test->get('image')); ?>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-lg-8">
            <label>Explanation</label>
            <?= $this->formRow($test->get('explanation')->setAttributes(['class' => 'form-control'])); ?>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-lg-8">
            <div onclick="return add_question()" class="btn btn-xs btn-info">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                Add a new question
            </div>
        </div>
    </div>

    <div class="form-group row" >
        <div class="col-lg-8">
            <label>Questions</label>
            <div id="questions">
                <?= $this->formCollection($test->get('questions')); ?>
            </div>
        </div>
    </div>

<input type="submit" name="submit" id="submitbutton" class="btn btn-primary" value="Submit" onclick="disableEmptyInput()">
<?= $this->form()->closeTag(); ?>

<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>

<script>
    function add_question() {
        var currentCount = $('#questions > fieldset > fieldset').length;
        var template = $('#questions fieldset span[data-template]').data('template');
        template = template.replace(/__index-question__/g, currentCount);
        $('#questions > fieldset').append(template);
        return false;
    }

    function disableEmptyInput() {
        // disable every empty option-inputs
        $('.option-input[type=text]').each(function(index) {
            if (! $(this).val().trim()) {
                $(this).siblings('input').prop('disabled', true);
                $(this).prop('disabled', true);
            }
        });
    }
</script>


<style>

.questionFieldset > fieldset{
    margin:30px 0;
}

.optionFieldset fieldset{
    margin: 10px 0;
    margin-left:50px;
}

.optionFieldset fieldset input[type=text]{
    width:590px;
    height: 34px;
    padding: 6px 12px;
    font-size: 14px;
    line-height: 1.428571429;
    color: #555;
    vertical-align: middle;
    background-color: #fff;
    background-image: none;
    border: 1px solid #ccc;
    border-radius: 4px;
    margin-right: 30px;
}

.optionFieldset fieldset input[type=checkbox]{
    width:20px;
    height: 34px;
    vertical-align: middle;
    margin-left: 10px;
}

.input-error + ul > li {
    border:1px solid red;
    color: red;
    list-style: none;
}

</style>