<?php


$form->setAttribute('action', $this->url('administration/tests', ['action' => 'addbis']));
$form->prepare();
$form->get('submit')->setValue('Add');

$test = $form->get('test');
$image = $test->get('image')->getValue();

echo $this->form()->openTag($form);



echo $this->formRow($test->get('id'));
echo $this->formRow($test->get('hash'));
echo $this->formRow($test->get('explanation'));
echo $this->formRow($test->get('image'));
echo $this->formCollection($test->get('questions'));

echo $this->formRow($test->get('tags'));

echo $this->formElement($form->get('submit'));

echo $this->form()->closeTag();
?>

<?php if (! empty($image)): ?>
    <div class="form-group row col-lg-8">
        <img src="/img/upload/<?= $image;?>" class="img-thumbnail"/>
    </div>
<?php endif; ?>