<?php
$form->setAttribute('action', $this->url('administration/tests', ['action' => 'edit', 'id' => $testId]));
$form->prepare();
$form->get('submit')->setValue('Edit');

$test = $form->get('test');
$image = $test->get('image')->getValue();

?>

<div class="page-header">
    <h3>Edit Test</h3>
</div>

<?= $this->form()->openTag($form); ?>
<?= $this->formHidden($test->get('id')); ?>

    <div class="form-group row">
        <div class="col-lg-8">
            <label>Tags</label>
            <div>
            <?= $this->formRow($test->get('tags')); ?>
            </div>
        </div>
    </div>

    <?php if (! empty($image)): ?>
    <div class="form-group row col-lg-8">
        <img src="/img/upload/<?= $image;?>" class="img-thumbnail img-max-height"/>
    </div>
    <?php endif; ?>

    <div class="form-group row">
        <div class="col-lg-8">
            <label>Image</label>
            <?= $this->formRow($test->get('image')); ?>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-lg-8">
            <label>Explanation</label>
            <?= $this->formRow($test->get('explanation')->setAttributes(['class' => 'form-control'])); ?>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-lg-8">
            <div onclick="return addQuestion()" class="btn btn-xs btn-info">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                Add question
            </div>
        </div>
    </div>

    <div class="form-group row" >
        <div class="col-lg-8">
            <label>Questions</label>
            <div id="questions">
                <?= $this->questionCollection($test->get('questions')); ?>
            </div>
        </div>
    </div>

<input type="submit" name="submit" id="submitbutton" class="btn btn-primary" value="Submit" onclick="disableEmptyInput()">
<?= $this->form()->closeTag(); ?>