


<div ng-app="quizz">

    <div class="front-flashMessenger">
        <?= $this->flashMessenger()->render('default', ['alert', 'alert-dismissible', 'alert-success']); ?>
        <?= $this->flashMessenger()->render('success', ['alert', 'alert-dismissible', 'alert-success']); ?>
        <?= $this->flashMessenger()->render('error', ['alert', 'alert-dismissible', 'alert-danger']); ?>
    </div>


    <div ng-controller="quizzController as ctrl" class="container container-main">

        <div class="image-container">
            <img ng-src={{'/img/upload/'+ctrl.getCurrentTest().image}} class="row test-image"  alt="{{ctrl.getCurrentTest().alt}}"/>

            <div ng-show="ctrl.state === 1" class="explanation-row">
                <div class="explanation">
                    {{ctrl.getCurrentTest().explanation}}
                    <p>réponse : {{ctrl.getCurrentTest().solutions | optionsMappingFilter : ctrl.optionsMapping}}</p>
                </div>
            </div>
        </div>

        <div ng-class="{'alert-success': ctrl.validator.valid, 'alert-danger': ! ctrl.validator.valid, 'visible': ctrl.state, 'visible-hidden': ! ctrl.state }"
             class="msg alert"
             id="msg-answer"
             role="alert">
            {{ctrl.validator.valid | validation}}
        </div>

        <div class="pull-right count">
            {{ctrl.collector.correct}} <span class="green glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            {{ctrl.collector.wrong}} <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
        </div>

        <div class="clearfix"></div>

        <div class="questions">
            <div ng-repeat="question in ctrl.getCurrentTest().questions">
            {{question.text}}
            <ul>
                <li class="option" ng-repeat="option in question.options"
                    ng-class="{active: ctrl.isActiveOption(option.id), correct: ctrl.state && ctrl.isCorrectOption(option.id), wrong: ctrl.state && ctrl.isWrongOption(option.id)}"
                    >
                    <div ng-click="ctrl.addAnswer(option.id)">
                        <button class="button-option">{{ctrl.optionsMapping[option.id]}}</button>
                        {{option.text}}
                    </div>
                </li>
            </ul>
            </div>
        </div>

        <div class="round-button round-button-validate pull-right" ng-click="ctrl.nextTest()" ng-class="{'round-button-next': ctrl.state}"><div class="round-button-content">{{ctrl.state | next}}</div></div>
    </div>

</div>

<script>
    (function(){
        'use strict';
        angular.module('testsInitService', [])
            .factory('getTestsJsonService', function(){
                return function() {
                    return <?= $testsJson ?>;
                }
            })
        ;
    })();
</script>