<?php
$commentForm->setAttribute('action', $this->url('post', ['url' => $post->getUrl()]));
$commentForm->setAttribute('method', 'post');
$commentForm->prepare();
?>

<div class="col-sm-8 blog-main">

        <div class="blog-post box-shadow">
            <h2 class="blog-post-title"><span><?= $post->getTitle(); ?></span></h2>
            <p class="blog-post-meta"><?= $post->getCreated()->format('M n Y'); ?></p>
            <?php if ($post->getImage()): ?>
            <img class="img-responsive" src="<?= $this->basePath(sprintf('img/upload/%s', $post->getImage())); ?>"/>
            <?php endif;?>
            <br>
            <div class="blog-post-text"><?= $post->getText(); ?></div>

            <?= $this->partial('partial/edit.phtml', [ 'post'=>$post ]); ?>

            <h2>Comments :</h2>


            <?= $this->form()->openTag($commentForm); ?>

            <?= $this->formRow($commentForm->get('csrf')); ?>

            <div class="form-group row">
                <div class="col-lg-12"><?= $this->formRow($commentForm->get('captcha')->setAttributes(['class'=>'form-control'])); ?></div>
            </div>

            <div class="form-group row">
                <div class="col-md-6"><?= $this->formRow($commentForm->get('name')->setAttributes(['class'=>'form-control'])); ?></div>
                <div class="col-md-6"><?= $this->formRow($commentForm->get('email')->setAttributes(['class'=>'form-control'])); ?></div>
            </div>

            <div class="form-group row">
                <div class="col-lg-12"><?= $this->formRow($commentForm->get('text')->setAttributes(['class'=>'form-control'])); ?></div>
            </div>

            <div class="form-group row">
                <div class="col-lg-3"><?= $this->formRow($commentForm->get('submit'))?></div>
            </div>


            <?= $this->form()->closeTag(); ?>


            <div class="comments">
            <?php foreach ($post->getComments() as $comment) : ?>
                <?php if (! $comment->isDeleted()): ?>
                    <div class="comment">
                        <span class="comment-author"><?= $comment->getName(); ?></span>
                        <span class="comment-metadata"><?= $comment->getCreated()->format('M n Y H:i:s'); ?></span>
                        <div class="comment-content"><?= $comment->getText(); ?></div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
            </div>
        </div>

</div>