<?php
$commentForm->setAttribute('action', $this->url('post', ['url' => $post->getUrl()]));
$commentForm->setAttribute('method', 'post');
$commentForm->prepare();
?>

<div class="col-sm-8 blog-main">

        <div class="blog-post box-shadow">
            <h2 class="blog-post-title"><span><?= $post->getTitle(); ?></span></h2>
            <p class="blog-post-meta"><?= $post->getCreated()->format('M n Y'); ?></p>
            <?php if ($post->getImage()): ?>
            <img class="img-responsive" src="<?= $this->basePath(sprintf('img/upload/%s', $post->getImage())); ?>"/>
            <?php endif;?>
            <br>
            <div class="blog-post-text"><?= $post->getText(); ?></div>

            <?= $this->partial('partial/edit.phtml', [ 'post'=>$post ]); ?>

            <h2>Comments :</h2>

            <?= $this->form()->openTag($commentForm); ?>

            <?= $this->formRow($commentForm->get('csrf')); ?>

            <?= $this->formRow($commentForm->get('captcha')); ?>

            <?= $this->formRow($commentForm->get('name'))?>

            <?= $this->formRow($commentForm->get('email'))?>

            <?= $this->formRow($commentForm->get('text'))?>

            <?= $this->formSubmit($commentForm->get('submit'))?>

            <?= $this->form()->closeTag(); ?>

            <?php foreach ($post->getComments() as $comment) : ?>
            <?= $comment->getText(); ?>
            <?php endforeach; ?>
        </div>

</div>