
<div class="col-sm-8 blog-main">

        <div class="blog-post box-shadow">
            <h2 class="blog-post-title"><span><?= $post->getTitle(); ?></span></h2>
            <p class="blog-post-meta"><?= $post->getCreated()->format('M n Y'); ?></p>
            <img class="img-responsive" src="<?= $this->basePath(sprintf('img/upload/%s', $post->getImage())); ?>"/>
            <br>
            <div class="blog-post-text"><?= $post->getText(); ?></div>

        </div>

</div>