<?php
$this->headTitle('Connexion');

$form = $this->form;
$form->setAttribute('class','form-horizontal');
$form->prepare();
?>

<?= $this->form()->openTag($form); ?>

    <h2 class="form-signin-heading">Identification</h2>
    <div class="form-group">
        <div class="col-lg-3">
        <?= $this->formRow($form->get('login')->setAttributes(['placeholder'   => 'Identifiant', 'class' => 'form-control'])); ?>
        </div>
    </div>

    <div class="form-group">
        <div class="col-lg-3">
        <?= $this->formRow($form->get('password')->setAttributes(['placeholder'   => 'Mot de passe', 'class' => 'form-control', 'autocomplete' => "off"])); ?>
        </div>
    </div>

    <div class="form-group">
        <div class="col-lg-3">
            <button class="btn btn-large btn-primary btn-block" type="submit">Se connecter</button>
        </div>
    </div>

<?= $this->form()->closeTag(); ?>